### PR TITLE
Update Cloudflare learn more link

### LINKED ISSUE #120: Docs - changed URL for Cloudflare
In [the documentation about upstream providers](https://docs.pi-hole.net/guides/upstream-dns-providers/), there is a link to [More information on Cloudflare DNS](https://cloudflare-dns.com/#explanation). This just points to an app installation page.

It should probably be changed to point to https://cloudflare-dns.com/dns/#explanation which is an actual explanation on how Cloudflare DNS works.

(If I understood the first thing about Github, I'd make this change myself, but I don't, so I can't).

### PR DESCRIPTION
**Pull request by Mcat12**
Closes #120

### CODE REVIEW

**Comment by dschaper** [comment]
https://changelog.travis-ci.com/the-default-python-version-for-your-builds-is-now-3-6-97935

**Comment by dschaper** [comment]
I think we can drop `futures` now from the requirements?

**Comment by Mcat12** [comment]
We may need to make a PR to fix the dependencies and versions before this PR can go through.

**Comment by dschaper** [comment]
Yeah, left a comment on Team to see the better way to update things.

**Comment by Mcat12** [comment]
I've made #122 to fix this.

**Comment by Mcat12** [comment]
This PR is now ready for review.

**Pull request merged**
