### PR TITLE
Update client.md

### PR DESCRIPTION
**Pull request by pabz99**
Tried to make some steps a bit more beginner proof.

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [ ] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by yubiuser** [comment]
Thanks for the PR.

> Shutdown the server before making changes to the configuration file:

This is only necessary, if `SaveConfig = true` is set. 
Before adding the changes you made, I would rather discuss if the SaveConfig should be removed.

**Comment by DL6ER** [comment]
I agree with the idea of just removing `SaveConfig`. Users may not expect this to work like it does (replace the config on restart/stop)

**Comment by yubiuser** [comment]
@pabz99 

Could you please change the PR accordingly? Or close this one and open a new one with only the `SaveConfig` removed?

If you want me to do it that's also fine.

**Comment by pabz99** [comment]
@yubiuser will look into it today!

**Comment by pabz99** [comment]
@yubiuser & @DL6ER : very stupid question, but how do I update my own commit? Tried to edit it in Github Editor, but it says I need to be on that branch before I can edit it.

**Comment by yubiuser** [comment]
How did you do your first commit? I do all my PRs local on my PC and push those to my fork of the Pi-hole repository. 

I would revert the last commit and do a next commit.

**Comment by dschaper** [comment]
@pabz99 Update?

**Comment by yubiuser** [comment]
Closing due to inactivity. Feel free to re-open anytime.

**Pull request closed without merging**
