### PR TITLE
Dev patches

### PR DESCRIPTION
**Pull request by XhmikosR**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/contributing/).

---

Just a few CI updates. We should probably switch to Python > 3.7 later too, but I'm unsure what versions are available on Netlify.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@PromoFaux could you please change the Build Image on Netlify to 20.04?

**Comment by PromoFaux** [comment]
Done 

image

Still looking for a cache setting

**Comment by PromoFaux** [comment]
`PYTHON_VERSION` is set as an env var @ `3.7` in the Netlify settings, too. Not sure if that affects things, but that can also be upped to 3.8

**Comment by XhmikosR** [comment]
Hmm, then we set it in two places. I'd say just drop the environment variable and we keep runtime.txt or we also drop that?

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
