### PR TITLE
Add Bookworm to supported OS on Docs

### PR DESCRIPTION
**Pull request by clwgh**
**What does this PR aim to accomplish?:**

A user [has pointed out](https://discourse.pi-hole.net/t/supported-operating-systems-webpage-needs-updating/67842) that Pi-hole Docs does not list Bookworm as a supported OS.

This PR adds Bookworm to supported OS on Pi-hole Docs

**How does this PR accomplish the above?:**

Update prerequisites.md

**Link documentation PRs if any are needed to support this PR:**

Bookworm [is confirmed](https://discourse.pi-hole.net/t/raspberry-pi-os-bookworm-is-out-now-pihole-error-unsupported-os-detected-debian-12/65480/28) as officially supported.

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [X] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by yubiuser** [comment]
It seems like a `netlify` issue.

> 1:46:24 PM: Failed during stage "preparing repo": For more information, visit https://docs.netlify.com/configure-builds/troubleshooting-tips/#build-fails-with-error-128: fatal: unable to access "https://github.com/pi-hole/docs/": Failed to connect to github.com port 443: No route to host
: exit status 128

How can we trigger a re-run?

**Comment by DL6ER** [comment]
I requested a re-run about two hours ago and this lead to the comment by @netlify immediately above. However, they do not appear to have really re-ran the jobs as they still show status failed 5 hours ago. I tried re-running a few times. It does seem to do *something* but the new status doesn't seem to get through to Github.

grafik

**Comment by clwgh** [comment]
Is this caused by something I've done or not done in my PR? Or is GitHub feeling poorly?

**Comment by DL6ER** [comment]
I think it is a Netlify bug not being able to clean up its mess it caused because it screwed up in a place where it usually doesn't screw up. I will try closing/re-opening the PR to see if this has any effect. Otherwise, I'd be fine with overwriting the tests using admin privileges at merge time as this is clearly not our fault.

**Comment by DL6ER** [comment]
Well, it did restart all the tests that were fine anyway but not the netlify ones...

grafik

**Comment by rdwebdesign** [comment]
This seems to be an issue with Netlify (`Failed to connect to github.com port 443: No route to host`):

```
9:46:24 AM: Failed during stage "preparing repo": For more information, visit https://docs.netlify.com/configure-builds/troubleshooting-tips/#build-fails-with-error-128: fatal: unable to access "https://github.com/pi-hole/docs/": Failed to connect to github.com port 443: No route to host
```

**Comment by rdwebdesign** [comment]
We also should remove Buster.

The Raspberry Pi OS page doesn't list Buster and PHP repos for Raspbian Buster are gone (https://packages.sury.org/php/dists/).

**Review by DL6ER — COMMENTED** [review]
A completely different idea: How about removing the table overall? Instead we add a listing like

```
The following operating systems are **officially** supported:
- Raspberry Pi OS <br>(formerly Raspbian)
- Armbian OS
- Ubuntu
- Debian
- Fedora
- CentOS Stream

Pi-hole only supports actively maintained versions of these systems.
```

**Comment by yubiuser** [comment]
I think this is a good idea. We avoid needing to change the table every 6 months. 
It's enough to remember to update `versions.txt` and add the tox tests.

**Comment by rdwebdesign** [comment]
I agree, but with one reservation:

If we do this, we will need to define what "actively maintained versions" means.
Will the support end on the "End of life" date? end of "Long Term Support"? end of "Extended Long Term Support"?

**Comment by DL6ER** [comment]
We can leave this open intentionally. "End of life" means something different for every distribution. Some have extended security updates (but no regular new features), some have paid prolonged support. Detailing this for every flavor seems over the top.

**Comment by rdwebdesign** [comment]
> "End of life" means something different for every distribution.

This is my concern... every user will want that their OS/distribution should be supported.

We will avoid changing the table every 6 months, but we will need to explain over and over why some OS is not supported.

**Comment by DL6ER** [comment]
I guess that's fine - can be a "canned reply". At least we won't have outdated documentation all the time...

**Comment by yubiuser** [comment]
Remember: there is no right to demand support for any given OS version. We are free to give or withdraw.

**Comment by yubiuser** [comment]
Added the PR: https://github.com/pi-hole/docs/pull/1110

**Comment by yubiuser** [comment]
Closing in favour of https://github.com/pi-hole/docs/pull/1110

**Pull request closed without merging**
