### PR TITLE
Make main text font-size bigger.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
Manual Netlify preview... <https://dazzling-montalcini-7a7d2f.netlify.com/>

**Comment by XhmikosR** [comment]
I left the nav items to still use pixels, although this isn't good because it doesn't respect one's browser font setting.

**Comment by dschaper** [comment]
The bullet block in the proposed feels different to me. The contrast between the bold points and the plain text is missing in the proposed view.

Current:
Annotation 2020-01-29 100850

_____

Proposed:
Annotation 2020-01-29 100924

**Comment by XhmikosR** [comment]
>The bullet block in the proposed feels different to me. The contrast between the bold points and the plain text is missing in the proposed view.

I didn't touch that as you can see by the patch...

You should set up Netlify so that we have automated previews.

**Comment by dschaper** [comment]
I think the difference is in the change of how the fonts are weighted.

And I'm working on Netlify, we need a Code of Conduct before we can apply.

**Comment by XhmikosR** [comment]
The thing is that 14px is way too small. Let alone that using pixel for font sizes is bad because it doesn't respect the user's browser option.

**Comment by dschaper** [comment]
Px to (r)em is fine. I'm just not sold yet on the weight. When I get a chance to play around with it I'll see if there's anything I like better.

**Comment by XhmikosR** [comment]
The weight is the same...

**Comment by dschaper** [comment]
Okay, font size, semantics... ;)

**Comment by XhmikosR** [comment]
Like I said, though, 14px is just too small. I can barely read the text on a 4K screen with 175% DPI.

Which is where rem comes into play.

**Comment by dschaper** [comment]
I understand that. I'm on a 4k scaled to 150% and can't see past my arm without glasses. Those screencaps are at that resolution.

**Comment by dschaper** [comment]
.7rem for base, .8rem for bold?

**Comment by dschaper** [comment]
(And "Pi-hole is powered..." doesn't match any other style on the page but that's another PR.)

**Comment by XhmikosR** [comment]
Why would we change the font-size for bold?

**Comment by dschaper** [comment]
Because I want more definition between the bold and the plain. That's what the px layout has and what I'd like in the relative version.

**Comment by XhmikosR** [comment]
It doesn't make any sense... Bold is already something that stands out. First time I hear about changing the font-size based on the font-weight.

**Comment by dschaper** [comment]
I guess I'm not conveying my thoughts and wishes properly. Pixel has a stark difference between the bold leading phrase and the following plain text. That is missing in the relative version. The relative version all just visually looks the same.

**Comment by XhmikosR** [comment]
I don't see any difference on my machine.

You can always play with different fonts. https://github.com/pi-hole/docs/blob/0cb0ff110cf78767a6b69bbe8afeb971d39fc416/mkdocs.yml#L12

Do note that what I used in this patch is not the theme default either https://squidfunk.github.io/mkdocs-material/specimen/

**Comment by dschaper** [comment]
Sounds good, I'll take a look later. And looking at https://crossbrowsertesting.com/open-source/ to get some views on different browsers and different platforms.

**Pull request merged**
