### PR TITLE
Updated query site

### PR DESCRIPTION
**Pull request by chriscn**
https://developers.cloudflare.com/1.1.1.1/dns-over-https/request-structure
My DNSoHTTPS wasn't working. Now it is fixed.

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [ ] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [ ] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes, and have included unit tests where possible.
- [ ] I am willing to help maintain this change if there are issues with it later.
- [ ] I give this submission freely and claim no ownership.
- [ ] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
Okay, quick question since you didn't actually provide any information or a basis for this.

How does a DNS server know that the DNS name of the upstream resolver is if it needs the upstream name to resolve it?

**Comment by chriscn** [comment]
I believe although I haven't been able to find any exact evidence for this that the `1.1.1.1/dns-query` has been deprechated in favour of `https://cloudflare-dns.com/dns-query`. This is stated in the [Cloudflare Documentation](https://developers.cloudflare.com/1.1.1.1/dns-over-https/request-structure)

**Comment by dschaper** [comment]
We'll need something more concrete to change the documentation. Can you find any official word that this is the case?

**Comment by chriscn** [comment]
I am struggling to understand why the [official documenation](https://developers.cloudflare.com/1.1.1.1/dns-over-https/request-structure) is not enough to change Pi-Hole documentation? When trying to setup cloudflared on my personal network; it would fail to resolve until I switched it to this new endpoint.

**Comment by PromoFaux** [comment]
`1.1.1.1/dns-query` still appears to work.

image

What Dan is saying is that if you're in a situation where the Pi-hole device is using Pi-hole as it's own nameserver, and your sole upstream is `cloudflared` pointing at `cloudflare-dns.com`.. how is it going to resolve that?

**Comment by dschaper** [comment]
The official documentation:

Screenshot_2020-12-27 Running a DNS over HTTPS client · 1 1 1 1 docs


>You can use numeric addresses, to avoid circular dependency on system resolver.

**Comment by DL6ER** [comment]
The last two comments show why this should not be merged. Closing. Thanks for your suggestion, anyway, we all learned something new (at least I did).

**Pull request closed without merging**
