### PR TITLE
Add navigation.indexes feature to mkdocs-material

### PR DESCRIPTION
**Pull request by PromoFaux**
### **What does this PR aim to accomplish?:**

Discussed internally, effectively saves a click by making linking the index to the main section header rather than having a subheader for overview/index.

thoughts

I've purposefully left the Docker section as I will be revamping that entire section in another PR

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by rdwebdesign** [comment]
What do you think about renaming the initial "Overview" to "About Pi-hole".

image

Like this:

image

**Review by yubiuser — COMMENTED** [review]
I think it is a bit inconsistently used: some item suse the index feature, others not (e.g. About Pihole, Getting Started). I think it should behave the same way everywhere.

**Comment by rdwebdesign** [comment]
> I think it is a bit inconsistently

That's why I suggested the change above.

**Comment by PromoFaux** [comment]
> I think it should behave the same way everywhere.

The difficulty here is inventing content for the index pages of those sections. I think the only ones where this appears inconsistent now are:

- `Getting Started`
- `Docker` (Will be addressed in another PR with more Docker docs)
- `Contributing`

**Comment by rdwebdesign** [comment]
> * Contributing

Every page under "Contributing" is related to code contribution in github. 

You can do the same as I suggested above to the initial page.
Remove "Contributing", move the content from "Contributing on GitHub" to the top level and fix the links:

contrib

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
