### PR TITLE
Update Projects.md

### PR DESCRIPTION
**Pull request by patski123**
Added link on how to enable/disable pi-hole from your iphone home screen.

### CODE REVIEW

**Comment by XhmikosR** [comment]
This seems to do some tracking `http://codeopolis.com/posts/how-to-control-pi-hole-from-your-iphone/?utm_source=docs.pi-hole.net&utm_medium=referral&utm_campaign=always-on+-+how+to+control+pihole+from+your+iphone&utm_content=textlink`

I wouldn't add it personally. Also it's not https and the last_updated change is not needed.

**Comment by PromoFaux** [comment]
Same blogpost was linked to on the subreddit, but different URL:

`http://codeopolis.com/control-pihole-from-phone`

Which expands out to:

`http://codeopolis.com/posts/how-to-control-pi-hole-from-your-iphone/?utm_source=reddit+r_pihole&utm_medium=social&utm_campaign=always-on+-+how+to+control+pihole+from+your+iphone&utm_content=post+-+link+submission`

Personally I would be more comfortable with the _direct_ post URL being used, and to echo @XhmikosR , there is really no excuse in this day and age for a site to be `http` over `https`

Direct link:
`http://codeopolis.com/posts/how-to-control-pi-hole-from-your-iphone/`

**Comment by XhmikosR** [comment]
>I placed a direct link in there instead. I got my permalinks mixed up. Also added HTTPS.

Works OK but make sure you update your image URLs to https too. There's the Velvet Update URLs which makes this a breeze (`http://codeopolis.com` - `https://codeopolis.com`)

**Comment by patski123** [comment]
Nice, that seemed to work perfectly!

**Pull request merged**
