### PR TITLE
Add steps for fixing unbound on bullseye

### PR DESCRIPTION
**Pull request by jaredmo**
## Thank you for your contribution to the Pi-hole Community! 

Please read the comments below to help us consider your Pull Request.

We are all volunteers and completing the process outlined will help us review your commits quicker.

**Please make sure you**
 1. Base your code and PRs against the repositories developmental branch.
 2. [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits as we enforce the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions

---
- **What does this PR aim to accomplish?:**

Added steps to fix unbound for Bullseye installations where `unbound-resolvconf.service` has already created `/etc/unbound/unbound.conf.d/resolvconf_resolvers.conf`

- **How does this PR accomplish the above?:**

Added steps and changed header description.

- **What documentation changes (if any) are needed to support this PR?:**

This is a doc change, so no additional changes required.

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
[ ] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by dschaper** [comment]
This is the test fail message:

```plain
markdownlint-cli2 v0.4.0 (markdownlint v0.25.1)
Finding: **/*.md !**/node_modules/**
Linting: 81 file(s)
Summary: 1 error(s)
docs/guides/dns/unbound.md:237 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```bash"]
Error: Process completed with exit code 1.
```

**Comment by jaredmo** [comment]
Thanks! I fixed it in the second commit.

**Comment by dschaper** [comment]
Thank you! I don't have a way to test this myself. @yubiuser or @jfb-pihole does this follow what your suggestions have been when troubleshooting?

**Comment by yubiuser** [comment]
Thanks for your contribution. This is a long-lasting open issue we wanted to address at some point.

The instructions are exactly what we use as quick troubleshooting help on discourse. 
However, I'm not sure how ` unbound-resolvconf.service` relate to the changes in seen with  resolvconf_resolver.conf` in bullseye and if this should all be in one paragraph.  I know that @jfb-pihole wanted to write a guide too. I'm sure he will review this PR when time permits.

**Comment by DL6ER** [comment]
@yubiuser @jfb-pihole Almost one year later I'm going to ping you about the status of this PR. Otherwise, I'm fine with merging it as is.

**Comment by yubiuser** [comment]
Superseded by https://github.com/pi-hole/docs/pull/834 and https://github.com/pi-hole/docs/pull/859

**Pull request closed without merging**
