### PR TITLE
replace blacklist with blocklist

### PR DESCRIPTION
**Pull request by Geezus42**
Change to more positive terminology.

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
Replace the term blacklist with blocklist.

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by yubiuser** [comment]
It's still called `blacklist` in Pi-hole. I think the documentation should reflect the identifiers used within the program. You also missed a lot of places within the documentation.

I think as long as Pi-hole uses `backlist/whitelist`, this PR should not be merged. If Pi-hole changes the terminology, the documentation should then follow.

**Comment by Geezus42** [comment]
You make a good point and I think it should be changed everywhere. This was just a quick submission as I was reading some documentation. I will try to be more comprehensive when I have some spare time to do so. I do however think at this point most people will know the terms are interchangeable and there is only a single letter difference, so I don't think it would truly affect people's understanding.

**Comment by PromoFaux** [comment]
https://github.com/pi-hole/docs/tree/release/v6.0

**Comment by dschaper** [comment]
> so I don't think it would truly affect people's understanding.

It will. Our users speak many different languages and changing the documentation so that it's out of sync with the actual web interface will cause us increased support loads that we just can't handle right now.

**Comment by DL6ER** [comment]
I agree with what has been said. However, this will mean that *a lot* of stuff breaks. Renaming on the front end only would be a mere band-aid fix, if we were to rename some things, this would have to be done everywhere. Items changing in the database and API **will** break user scripts, etc.

You're not the first one to suggest such a change. We've had a lot of discussions about this topic. They all came up after the (entirely unrelated) black-life-matters debate in the United States appeared. We're also had a few valued comments from actually black people that said: "I don't care about this change. It's the white people that think they know what the best is for the black that concerns me.". You can find these discussions on discourse.pi-hole.net

May your motivation have been removing explicitly `black` or not, you said

> Change to more positive terminology

I, personally, don't see block being any more positive than black.

But as @PromoFaux already mentioned, we're currently designing a new API and redesign how the most natural feeling of interacting with the Pi-hole is. And we're going to change from `black-/whitelist` to (probably) `denied and allowed domains`. This is going on for some longer time, and was decided even longer ago than when the black-life-matters debate started.

**Pull request closed without merging**
