### PR TITLE
Update dns-over-https.md

### PR DESCRIPTION
**Pull request by XhmikosR**
Remove the comments inside the snippet to make it easier to copy/paste and link to the cloudflared repo.

### CODE REVIEW

**Comment by dschaper** [comment]
Do the comments break a bash script? I don't think they would?

**Comment by XhmikosR** [comment]
They don't break the script, but it's extra noise if pasted...

**Comment by dschaper** [comment]
I'd keep the comments but the others may have a different view.

**Comment by XhmikosR** [comment]
As you wish, I shouldn't have added them in the first place 😛

**Pull request merged**
