### PR TITLE
Fix footer override

### PR DESCRIPTION
**Pull request by XhmikosR**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
I don't see the netlify logo/link in the footer of the deploy preview?

**Comment by XhmikosR** [comment]
There's no logo on the live site either https://docs.pi-hole.net/. This patch just moves the override and fixes the footer classes/reduces the overrides. Any further changes could/should be made later by someone else in the new main.html file which just overrides the block.

**Comment by dschaper** [comment]
Current Site:

Screenshot 2021-04-03 123231

This PR:
Screenshot 2021-04-03 123325

**Comment by XhmikosR** [comment]
Ah, you mean the text, not logo since there's no logo. Will look into it.

**Comment by dschaper** [comment]
Sorry, I could have been clearer. 

Yeah, I meant there is no logo or link.

**Comment by XhmikosR** [comment]
https://github.com/squidfunk/mkdocs-material/issues/2508

I'll probably revert back to overriding the footer.html file but it needs to be adapted probably frequently since right now it leads to broken result.

**Comment by dschaper** [comment]
Thanks!

**Comment by XhmikosR** [comment]
I asked upstream and based on what they plan to do I'll adapt this PR later. I find the block override solution much cleaner because the issue we hit right now wouldn't happen if it worked right. Otherwise, I'll just update the footer.html template.

**Comment by XhmikosR** [comment]
This was fixed upstream, so I switched to a block override. This is a lot cleaner IMHO, and it shouldn't break things so easily :)

**Review by dschaper — APPROVED** [review]

**Pull request merged**
