### PR TITLE
Update ci.yml

### PR DESCRIPTION
**Pull request by XhmikosR**
* run it for PRs and master branch only
* remove `fetch-depth` since we no longer build with Actions and we don't need this
* use double quotes

### CODE REVIEW

**Comment by XhmikosR** [comment]
Someone still needs to adapt branch protection rules @PromoFaux. #286 was merged without taking care of the TODO :/

**Comment by PromoFaux** [comment]
@XhmikosR what needs to change in the branch protection rules, please? Agreed about removing `gh-pages`

**Comment by XhmikosR** [comment]
I guess we only need the CI Action for pull requests only and the gh-pages
removed

**Comment by PromoFaux** [comment]
OK, should be done

**Comment by XhmikosR** [comment]
Feel free to merge then :)

**Comment by dschaper** [comment]
I merged #286 because a review was requested for it.

**Pull request merged**
