### PR TITLE
Add revision date to pages.

### PR DESCRIPTION
**Pull request by dschaper**
https://squidfunk.github.io/mkdocs-material/plugins/revision-date/

YAML front matter shouldn't be needed anymore.

### CODE REVIEW

**Comment by XhmikosR** [comment]
>YAML front matter shouldn't be needed anymore.

If this is true, you should remove the last_modified from all pages then :)

**Comment by dschaper** [comment]
We'll see once this merges. If it works then we can go clean up the other pages.

**Comment by XhmikosR** [comment]
As you wish, but the live site shouldn't be used for testing :P

**Comment by dschaper** [comment]
Welcome to Pi-hole! ;)

**Comment by XhmikosR** [comment]
It works fine AFAICT, i just don't get where the `last_updated` front matter value is/was used.

**Comment by dschaper** [comment]
Screenshot_2020-02-09 pi-hole docs

**Comment by XhmikosR** [comment]
I mean in the generated files.

**Comment by XhmikosR** [comment]
BTW forgot to say this adds more dependencies than the one you included.

**Comment by dschaper** [comment]
It built successfully, but it just includes the file date so it's always going be the date of the last build. Will probably revert this and look for another option.

**Comment by XhmikosR** [comment]
I meant that the requirements file only had the top level dependency :)

**Comment by dschaper** [comment]
Not sure I see what the issue is?

**Comment by XhmikosR** [comment]
That I thought we were listing all dependencies not only the top-level ones.

**Comment by dschaper** [comment]
Oh, okay, I'm with you now. I thought from our other conversation that we were going with top level only and letting those packages handle their dependencies.

**Comment by XhmikosR** [comment]
We didn't change that :)

That being said, the plugin does work locally. You shouldn't revert the patch. I think I know how to fix this

**Comment by dschaper** [comment]
Great! Glad there's an option to fix it.

As for requirements.txt, it can contain what is needed for things to work. I'm more interested in the final output and not a legalistic process to get there.

**Comment by XhmikosR** [comment]
We really need to have previews and not treat the live site like staging. It just is against my beliefs.

Regardless, I will make another PR, but we'll only know if it works after merging it anyway, so ignore the above comment for this one case :)

**Comment by dschaper** [comment]
The CoC is in process and we'll get Netlify once that is done. 

This is the documentation repository, things are a lot less regimental with this repository. That's just how Pi-hole works for this particular process.

**Pull request merged**
