### PR TITLE
Update markdownlint-cli2 dependency to 0.4.0, resolve violations of new rules for consistent emphasis.

### PR DESCRIPTION
**Pull request by DavidAnson**

### CODE REVIEW

**Comment by DL6ER** [comment]
Thanks, however, please do not modify `package-lock.json` (you actually downgraded it). Would it be possible to base your PR on top of the dependabot PR instead? So you'd just provide the difference needed to make the tests pass.

**Comment by DavidAnson** [comment]
Rebased onto `dependabot/npm_and_yarn/markdownlint-cli2-0.4.0` as requested.

**Comment by DavidAnson** [comment]
FYI, I made the minimum changes to establish emphasis consistency within each file (default rule behavior). If you want to enforce asterisk or underscore for emphasis across the project, you can configure that in `.markdownlint.json`, but there will be more changes required because both appear to be in use today.

**Review by DL6ER — APPROVED** [review]
Thanks!

**Comment by DL6ER** [comment]
@dschaper these changes come straight from the dependabot PR this branch is based on

**Comment by DavidAnson** [comment]
@dschaper, I already did that at @DL6ER's request. My commit touches only Markdown files and Dependabot's commit does whatever it does. Did I miss something?

**Comment by dschaper** [comment]
No, it's all good.

**Comment by DavidAnson** [comment]
Cool, thanks both!

**Pull request merged**
