### PR TITLE
Improve wireguard guide

### PR DESCRIPTION
**Pull request by DL6ER**
## Thank you for your contribution to the Pi-hole Community!

Please read the comments below to help us consider your Pull Request.

We are all volunteers and completing the process outlined will help us review your commits quicker.

**Please make sure you**

 1. Base your code and PRs against the repositories developmental branch.
 2. [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits as we enforce the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
 3. [Sign](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all your commits as they must have verified signatures
 4. File a pull request for any change that requires changes to [our documentation](https://docs.pi-hole.net/) at our [documentation repo](https://github.com/pi-hole/docs) 

---

**What does this PR aim to accomplish?:**

Improve wireguard guide

**How does this PR accomplish the above?:**

Do not restart the server when adding new clients to prevent interrupting existing peer connections.

`man wg`:
```
       syncconf <interface> <configuration-filename>
              Like  setconf,  but reads back the existing configuration first and only makes changes that are explic‐
              itly different between the configuration file and the interface. This is much less efficient than  set‐
              conf, but has the benefit of not disrupting current peer sessions. The contents of <configuration-file‐
              name> must be in the format described by CONFIGURATION FILE FORMAT below.
```

`man wg-quick`:

```
Use strip to output  a  configuration  file  with  all  wg-quick(8)-specific options removed, suitable for use with wg(8).
```

**Link documentation PRs if any are needed to support this PR:**

This is the documentation PR.

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [X] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Review by yubiuser — COMMENTED** [review]
Did this work for you? I read about `wg syncconf wg0 <(wg-quick strip wg0)` and it should work, however

```
rockpi@rockpi-4b:~$ sudo wg syncconf wg0 <(wg-quick strip wg0)
fopen: No such file or directory
```

The only other report regarding this issue I found is (search for `fopen`)
https://forums.openpli.org/topic/89867-tunnel-everything-through-wireguard/

**Comment by DL6ER** [comment]
The issue you're facing is that the `wg-quick strip wg0` is run without `sudo`. As the wireguard config files are only accessible with `root` permissions, this command correctly reports `No such file or directory`. Compare running `ls /etc/wireguard/wg0.conf` once with and once without `sudo`.

**Comment by yubiuser** [comment]
```
rockpi@rockpi-4b:~$  sudo wg syncconf wg0 <(sudo wg-quick strip wg0)
fopen: No such file or directory
```

I actually needed to be `root` for this to work. Should we add this information to
```
root@rockpi-4b:/home/rockpi# wg syncconf wg0 <(wg-quick strip wg0)
```

**Comment by DL6ER** [comment]
`systemctl restart wg-quick@wg0` is replaced by `wg syncconf wg0 <(wg-quick strip wg0)`.
There was no `sudo` before, either. The page runs at the very top `sudo -i`.

**Review by yubiuser — APPROVED** [review]
Let's not talk about my reading comprehension ...

**Pull request merged**
