### PR TITLE
Fixing Tabs config

### PR DESCRIPTION
**Pull request by rdwebdesign**
- **What does this PR aim to accomplish?:**

This PR fixes the visual error saw in #758

- **How does this PR accomplish the above?:**

Adding a missing configuration option.
183323698-10040aee-f0b7-4004-8711-bc4488d076b9

- **What documentation changes (if any) are needed to support this PR?:**

None

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Review by yubiuser — COMMENTED** [review]
Alternative proposal without indention

`#### Raspberry Pi`
`#### Linux`

Bildschirmfoto zu 2022-08-08 08-38-46

**Comment by rdwebdesign** [comment]
After a little sleep I decided to try the original Tab idea, using the correct config.

I think it's working as expected.

**Comment by yubiuser** [comment]
Looks better than before and fixes the footer issue (I guess). At least no warning in the dev tools. Please squash locally.

**Comment by rdwebdesign** [comment]
Superseded by #760.

**Pull request closed without merging**
