### PR TITLE
Move client.ovpn to the repo.

### PR DESCRIPTION
**Pull request by XhmikosR**
Move ovpn configuration from DL's website to locally stored.

### CODE REVIEW

**Comment by dschaper** [comment]
Hold for DL's review.

**Comment by XhmikosR** [comment]
I'm holding, I don't have push rights here anyway :)

**Comment by dschaper** [comment]
💯 Wasn't directed to you personally. Not sure if there's a reason for it being on dl.de or if that was just done out of convenience when it was hosted on the GitHub wiki.

**Comment by dschaper** [comment]
@DL6ER You might have missed this, I didn't ping you for it.

**Pull request merged**
