### PR TITLE
Update Nginx config for Pi-hole v5

### PR DESCRIPTION
**Pull request by MichaIng**
- The PHP SQLite module package is named `-sqlite3` on all supported APT-based distros:
  - https://packages.debian.org/php-sqlite
  - https://packages.ubuntu.com/php-sqlite
- PHP intl is required for Pi-hole v5.
- PHP zip module is not required for Pi-hole, but the xml module is.
- The webserver user requires R/W access to gravity.db since Pi-hole v5.

Signed-off-by: MichaIng <micha@dietpi.com>

### CODE REVIEW

**Comment by MichaIng** [comment]
And another question:
- Why does the config contain basic authentication?
- The admin panel itself has internal authentication already.
- The official Lighttpd config does not contain any additional authentication.

**Comment by PromoFaux** [comment]
> * Why does the config contain basic authentication?

From the top of the page: 

>**This is an unsupported configuration created by the community**

I can't say I've ever vetted it myself, not having ever used `nginx`

**Comment by MichaIng** [comment]
@PromoFaux 
It was just brought to my attention through this report on forum: https://discourse.pi-hole.net/t/see-no-stats-after-update-to-5-0/31920
Commenting the authentication seems to not solve it though, so I think it is best to have someone reviewing it that was involved creating this docs page.

Just to note, on DietPi (v6.30) Pi-hole works fine with Nginx, but we use a different config that is closer to the official Lighttpd one. I'll contribute some parts step-by-step, e.g. the curl -I debug header and blocking access to all dotfiles. However besides basic authentication I cannot see any critical difference that could break it from working, so the above linked issue likely is not about the Nginx config.

**Comment by PromoFaux** [comment]
Are you happy with the changes as they sit, or do you have more to add?

**Comment by MichaIng** [comment]
Lets merge it like this, so it is only about Pi-hole v5 + package name updates and does not touch the actual config.

I'll open separate PRs about config content changes and will pull in the original contributors for discussion about that.

**Pull request merged**
