### PR TITLE
Add Netlfiy badge to README.md

### PR DESCRIPTION
**Pull request by dschaper**

### CODE REVIEW

**Comment by dschaper** [comment]
Not sure why the deploy steps are failing. The log shows nothing.

**Comment by XhmikosR** [comment]
Yeah the failure seems unrelated to this PR. But let me test something

**Comment by XhmikosR** [comment]
Not sure why this happens.

Although the change of this PR isn't 100% right. We don't use Netlify for the production branch. We only use Netlify for PR previews.

**Comment by dschaper** [comment]
Needs to be on the README for the OSS package with Netlify.

**Comment by XhmikosR** [comment]
> Needs to be on the README for the OSS package with Netlify.

I know, I just wanted to point out it's not 100% right. The production deployments use GitHub pages 🙂

**Comment by dschaper** [comment]
Noted, not sure why it matters though.

**Comment by XhmikosR** [comment]
Not sure it matters, I'm just pointing out it's not true 😛

**Comment by dschaper** [comment]
Okay, forget it then.

**Comment by XhmikosR** [comment]
If it's required just add it, it's no big deal. Although, personally I'd
contact them and see if they have a different requirement when one is using
only PR previews.

**Comment by dschaper** [comment]
We're being charged for Netlify.

**Pull request merged**
