### PR TITLE
Update dns-over-https.md

### PR DESCRIPTION
**Pull request by ThinkPadNL**
Added 1.0.0.1 also, for more redundancy.

Signed-off-by: ThinkPad <12446338+ThinkPadNL@users.noreply.github.com>

### CODE REVIEW

**Comment by PromoFaux** [comment]
@ThinkPadNL thanks for the submission. Please can you append:

```
Signed-off-by: ThinkPadNL <YourEmailAddressHere>
```

to the OP of this PR? Sorry if it seems silly, we require all contributions to have signed off commits. If you add it to the PR, then we can ignore the DCO bot's complaints!

Cheers

**Comment by ThinkPadNL** [comment]
@PromoFaux Does it really need my private address? I don't want that to be listed publicly on GitHub...

**Comment by dschaper** [comment]
GitHub assigns you a private email address that you can use. It's the one ending in `@users.noreply.github.com`. You can find it under your GitHub account settings > Email.

**Comment by ThinkPadNL** [comment]
@dschaper Thanks for pointing me on that one! I just added the original message. Is it correct now?

**Pull request closed without merging**
