### PR TITLE
Update unbound.md

### PR DESCRIPTION
**Pull request by deHakkelaar**
`/var/lib/unbound/root.hints` gets stored with `pi` user ownership:

```
pi@ph5:~ $ stat /var/lib/unbound/root.hints
[..]
Access: (0644/-rw-r--r--)  Uid: ( 1000/      pi)   Gid: ( 1000/      pi)
```

This adjustment will write it as the `root `user:

```
pi@ph5:~ $ stat /var/lib/unbound/root.hints
[..]
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
```

### CODE REVIEW

**Comment by dschaper** [comment]
Is there a reason it needs to be owned by `root`? The file should only ever be read.

**Comment by deHakkelaar** [comment]
Common security practice idk ?
Most all files in that `/var/lib/` folder are owned by root.

**Comment by deHakkelaar** [comment]
Monkey see monkey do  ;)

**Comment by dschaper** [comment]
I'm not comfortable doing a `wget` or `curl` as root directly in to a file location like that. 

Not saying the existing instructions are all that much better but `sudo curl` is a red flag to me.

If you wanted to make it one line then something like `wget https://www.internic.net/domain/named.root -qO- | sudo tee /tmp/tee` which would show you exactly what is being written to the `tee` location?

**Comment by deHakkelaar** [comment]
I tested and that should do the job just fine.
Shall I create a new pull ?

**Comment by deHakkelaar** [comment]
Ow dont need to I see.
I altered in what you proposed.
Not that used to github ;)

**Review by dschaper — APPROVED** [review]

**Pull request merged**
