### PR TITLE
Update prerequisites.md

### PR DESCRIPTION
**Pull request by GAS85**
As per discussion [here](https://github.com/pi-hole/pi-hole/issues/3356), was [mentioned](https://github.com/pi-hole/pi-hole/issues/3356#issuecomment-649213023) that needed packages are listed in a prerequisites, but it is not. Should we added them?

### CODE REVIEW

**Comment by dschaper** [comment]
If you look further down at the port requirements, specifically port 80:

>If you have another Web server already running, such as Apache, Pi-hole's Web server will not work. You can either disable the other Web server or change the port on which `lighttpd` listens, which allows you keep both Web servers running.

**Comment by GAS85** [comment]
The point is that dependencies are missing when user decides to not use build in web server. May be it is better to move dependencies note to the port 80 section?

**Comment by DL6ER** [comment]
I do not really understand this change. Why do you want to install these packages when you are not installing the web interface? When you need them in a custom web server (like `apache2`), then that's a valid reason. However, looking at your change, it looks like you're trying to say they are *always* needed when not installing the web interface (so also when not using the web interface at all). This is not correct.

**Comment by GAS85** [comment]
As per [this](https://github.com/pi-hole/pi-hole/issues/3356) comment pdo file is a part of the installation script for some cases, but not listed in a document. Yes, it could be that it is not always needed, but it is in some cases and should be highlighted for this purpose.

**Pull request closed without merging**
