### PR TITLE
Remove last_updated front matter key.

### PR DESCRIPTION
**Pull request by XhmikosR**
This seems unused ATM

### CODE REVIEW

**Comment by XhmikosR** [comment]
Ping @dschaper

**Comment by dschaper** [comment]
I'd prefer they stay.

**Comment by XhmikosR** [comment]
I don't see the point. There's git log and the mkdocs plugin.

**Comment by dschaper** [comment]
Understood, but it doesn't harm anything to have them there.

**Comment by DL6ER** [comment]
Who is responsible for updating them? As they are in the md files, do I have to update them manually? Are there any consequences when I forget to do this?

**Comment by XhmikosR** [comment]
They aren't used at all. They don't offer anything...

**Comment by PromoFaux** [comment]
Err, is it not this? 

image

**Comment by XhmikosR** [comment]
No, that's based on the git commit date.

**Comment by PromoFaux** [comment]
Yeah, no I can see that now. 

> Who is responsible for updating them? As they are in the md files, do I have to update them manually?

Looking at it, yes. But the headers are not on every page, so.. only sometimes. I don't know. I'm not 100% what purpose it serves to be honest, considering each page has a last updated date at the bottom anyway. 🤷‍♂️

**Comment by XhmikosR** [comment]
Like I said, they are not used!

> No, that's based on the git commit date which is retrieved automatically on build time with mkdocs-git-revision-date-localized-plugin.

**Comment by PromoFaux** [comment]
Well, let's put a pin in it for now. They're not doing any harm where they are, we can revisit it at some unspecified point in the future

**Comment by XhmikosR** [comment]
Yeah, I don't mind, I just wanted to explain to everyone that they do nothing so there's no need to update them. Which is why I made this PR in the first place, to avoid confusion.

**Comment by dschaper** [comment]
So the plugin to build multiple versions of the documentation is fixed now and can use `git` dates?

**Comment by XhmikosR** [comment]
That I don't know, I haven't even tried that, nor do I see an issue about switching plugins.

I only know that the current frontmatter values are outdated and aren't used. If they are needed again, we could add them, but the current situation is confusing, as you can see.

That being said, feel free to leave the keys, I don't really mind.

**Pull request closed without merging**
