### PR TITLE
removed script extension (.sh) for the cron files

### PR DESCRIPTION
**Pull request by Jinnmv**
The cron.weekly scripts are started by run-parts which skips all files with extension.
https://serverfault.com/questions/408093/why-does-cron-weekly-not-run

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
*not applicable for the documentation update*
- [ ] I have tested my proposed changes, and have included unit tests where possible.
*not applicable for the documentation update*
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*Fix the issue in the documentation. Cron doesn't run scripts with extension in file name (https://serverfault.com/questions/408093/why-does-cron-weekly-not-run)*

**How does this PR accomplish the above?:**
*Documentation is updated to propose using file name without extension for the cron task `/etc/cron.weekly/cloudflared-updater.sh -> /etc/cron.weekly/cloudflared-updater`*

**What documentation changes (if any) are needed to support this PR?:**
*the changes are in the documentation*

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by DL6ER** [comment]
The update instructions (with `.sh`) were added by @iUnknwn in https://github.com/pi-hole/docs/commit/70d0d13c892cf3b51803b28dae5a6adbb45c26a3.

I guess this should be fine. Have you checked whether the scrip runs?

**Comment by dschaper** [comment]
You should be able to run `run-parts -v --test /etc/cron.weekly` to see what scripts will be run.

**Comment by dschaper** [comment]
```bash
dan@raspberrypi:/etc/cron.weekly $ run-parts -v --test /etc/cron.weekly
/etc/cron.weekly/man-db
/etc/cron.weekly/test
dan@raspberrypi:/etc/cron.weekly $ ls -la /etc/cron.weekly/
total 16
drwxr-xr-x  2 root root 4096 Mar  1 11:32 .
drwxr-xr-x 94 root root 4096 Feb 27 19:39 ..
-rwxr-xr-x  1 root root  813 Feb 10  2019 man-db
-rw-r--r--  1 root root  102 Oct 11  2019 .placeholder
-rwxr-xr-x  1 root root    0 Mar  1 11:32 test
-rwxr-xr-x  1 root root    0 Mar  1 11:31 test.sh
```

**Review by dschaper — APPROVED** [review]

**Comment by iUnknwn** [comment]
Apologies for the late reply (and for the error, this is embarrassing). I checked on my system, and when I wrote the scripts and doc I forgot I had an old entry for the script in crontab, so it was running from there and didn't realize it wasn't running from cron.weekly. 

Thank you for catching that!

**Pull request merged**
