### PR TITLE
Update cloudflared.md

### PR DESCRIPTION
**Pull request by pixolin**
The proposed software has a bug that stops it from working on some Raspberry Pi models. I have added a note and suggested the use of an older version as a workaround.

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*Inform users about a bug in the proposed software.*

**How does this PR accomplish the above?:**
*Ads a note in the documentation.*

**What documentation changes (if any) are needed to support this PR?:**
*This* **is** *the documentation change.* 😀

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
Is there something authoritative we can look at to make sure the URL for the download is legit?

**Comment by pixolin** [comment]
I can only refer to the discussion of a GitHub issue at https://github.com/cloudflare/cloudflared/issues/38.

**Comment by dschaper** [comment]
I'd rather link to that Issue or to the specific comment from Cloudflare at https://github.com/cloudflare/cloudflared/issues/38#issuecomment-687743958 instead of linking to a binary directly.

**Comment by pixolin** [comment]
Absolutely fine for me. Do you want me to rephrase and make a new pull request?

**Comment by dschaper** [comment]
Actually, seeing that the guide already pulls from that same organization, I guess it's okay.

**Review by dschaper — APPROVED** [review]

**Pull request merged**
