### PR TITLE
Switch to GitHub Actions CI

### LINKED ISSUE #229: Switch to GitHub Actions CI
So that everything is controlled through the repo settings including secrets.

I can make a PR but I don't know how to test it...

References:

* https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-static-site-generators-with-python

### PR DESCRIPTION
**Pull request by XhmikosR**
Closes #229

### CODE REVIEW

**Comment by XhmikosR** [comment]
@DL6ER @PromoFaux: please have a look when you can. We tested this and it works fine so far. I want to have another look tomorrow with a clear mind just in case I missed something.

**Comment by XhmikosR** [comment]
Note to self, try splitting the deploy from the build action.

**Comment by dschaper** [comment]
> We tested this and it works fine so far.

That's XhmikosR and myself that checked things over.

**Comment by XhmikosR** [comment]
The relevant gh-pages push https://github.com/pi-hole/docs/commit/28271017941e473439c1c3c0d22449113edac3ce

**Comment by DL6ER** [comment]
As far as I can see, the existing flow works for quiet some time. What are the benefits of switching to GitHub Actions?

**Comment by dschaper** [comment]
Actually working. :) Travis is wonky at times and lately has been refusing to build with warnings of `abuse`. 
Screenshot_2020-02-04 pi-hole docs - Travis CI

**Comment by dschaper** [comment]
Looks good now. @DL6ER are you okay with changing this over from Travis to GitHub Actions?

**Comment by DL6ER** [comment]
I don't feel all that comfortable but this may be entirely related to me not knowing Github Actions and not having enough time to work it out. If you say this is sound and similar (or even better) to the schema we have right now, you will not hear a No-No from my side.

**Comment by dschaper** [comment]
Yes, I'm comfortable with it. There's a lot that Actions can do now for other tasks. 

https://github.com/sdras/awesome-actions

And a short intro: https://lab.github.com/github/hello-github-actions!

**Pull request merged**
