### PR TITLE
Change to Pi-hole colors

### PR DESCRIPTION
**Pull request by dschaper**
Signed-off-by: Dan Schaper <dan.schaper@pi-hole.net>

### CODE REVIEW

**Comment by XhmikosR** [comment]
I don't see any difference with this patch?

**Comment by dschaper** [comment]
I do.

**Comment by XhmikosR** [comment]
Can you demonstrate it with a screenshot please?

**Comment by dschaper** [comment]
https://squidfunk.github.io/mkdocs-material/getting-started/#color-palette

**Comment by XhmikosR** [comment]
That I know, but I don't see any difference locally with this patch. :S

**Comment by dschaper** [comment]
Lets see what happens then.

**Comment by dschaper** [comment]
Looks like the documentation isn't accurate then!

**Comment by XhmikosR** [comment]
Yup. This should probably be reverted in the meantime.

**Comment by dschaper** [comment]
See #245

**Pull request merged**
