### PR TITLE
Add FAQ

### PR DESCRIPTION
**Pull request by clwgh**
**What does this PR aim to accomplish?:**

It adds a FAQ which explains the order in which locally defined DNS is used. This useful piece of info was [mentioned on discourse](https://discourse.pi-hole.net/t/hostnames-instead-of-ip-in-the-dashboard-etc-hosts-edition/66068/2) and I felt it was worth capturing explicitly in documentation.

**How does this PR accomplish the above?:**

Edits made to faq.md

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
4. I have commented my proposed changes within the code and I have tested my changes.
5. I am willing to help maintain this change if there are issues with it later.
6. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
7. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
8. I have checked that another pull request for this purpose does not exist.
9. I have considered, and confirmed that this submission will be valuable to others.
10. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
11. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by yubiuser** [comment]
Thanks for your PR. 

I think adding the order of locally defined hosts is valuable addition to the FAQ. However, I'm not convinced your other changes (Index, Back to top) are necessary, because we have the sticky ToC on the side. This is the de-facto index and also provides quick links to each item. Why would I want to jump to the top again?

Screenshot at 2023-11-09 20-29-44

**Comment by rdwebdesign** [comment]
I agree with yubiuser: The Index block and "back to top" links are unnecessary.

- In desktops, page topics are shown on the right side.
- In mobile, the topics can be accessed using the main menu:
  image

**Comment by clwgh** [comment]
Thanks for the update. I've been dipping into the Pi-hole docs for years and have never noticed a TOC on the right-hand side! I agree that does the job that I was trying to achieve. I have edited faq.md to remove the Index and the Back to top links, leaving just the new FAQ at the end, and merged it into this PR.

**Comment by yubiuser** [comment]
Thanks. Can you please squash all the commits down?

**Comment by clwgh** [comment]
I cannot find the squash option anywhere in the web client. I'm closing this PR and will open a new one with the single commit.

**Comment by rdwebdesign** [comment]
If you are using the Github Web interface to commit, there is no way to rebase/squash your commits. You can do it using `git` on the command line.

**Comment by clwgh** [comment]
Yes I did it all in the web interface for convenience, but it looks like it's backfired in that case!

**Comment by rdwebdesign** [comment]
In this case, you could clone the repo (containing all your commits) to your local machine, use `git` to rebase and squash the commits into a single one and them *force push* the "squashed" commit.

**Comment by clwgh** [comment]
I'll know for next time. I have a feeling that the web client is okay for discussion but best avoided for workflow, which is better using `git` directly. Seems a daft omission for them not to support squashing commits in the web client prior to a PR.

**Pull request closed without merging**
