### PR TITLE
Add 'How to fork and rebase'

### PR DESCRIPTION
**Pull request by yubiuser**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
---

**What does this PR aim to accomplish?:**
Adds info from https://github.com/pi-hole/pi-hole/pull/3178 (https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md) to the docs also.

### CODE REVIEW

**Comment by DL6ER** [comment]
I wonder if one of the two should be a link to the other. If they exist in two places we **will** forget to update one if we update the other

**Comment by yubiuser** [comment]
Yeah, good point. 

I would prefer to keep the docs, as they also contain a how to sign off.

P.S. https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project might be removed as well (already stating: TO BE REMOVED (already ported))

**Comment by DL6ER** [comment]
> P.S. https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project might be removed as well (already stating: TO BE REMOVED (already ported))

R.I.P.

**Comment by dschaper** [comment]
Probably should have something at that wiki URL that links to this. I know it drives me nuts to search for something, be given a link to a Wiki and then the Wiki is gone with only a general "Go here and do another search" entry.

**Comment by DL6ER** [comment]
Done

**Comment by dschaper** [comment]
Thanks, and then after this PR is merged then https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md will link to the docs.pi-hole.net location?

**Review by dschaper — DISMISSED** [review]

**Comment by XhmikosR** [comment]
It seems there are links to a non-existent anchor `#forking-and-cloning-from-github-to-github`

**Comment by yubiuser** [comment]
Aren't the headers implicit anchors? In the preview the links are working....

**Comment by XhmikosR** [comment]
Ah, true, you are basically linking to the top heading. All good then, I guess 👍

**Comment by yubiuser** [comment]
I've rebased on master and added all info from https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md

If this is merged, the Info from the wiki can be removed and be replaced with a link to the docs.

Side note: I'll go ahead and remove all sites from the wiki that have been transferred already

**Comment by yubiuser** [comment]
Ready for merge.

**Pull request merged**
