### PR TITLE
update nginx-configuration.md

### PR DESCRIPTION
**Pull request by anakuron**
added missing package php-sqlite3 to necessary packages, updated all php7.0 versions to php7.3 for since it's now the default in rasbian

### CODE REVIEW

**Comment by dschaper** [comment]
Close/reopen to kick Travis.

**Comment by dschaper** [comment]
Moving from Travis to Actions. Travis is showing this PR as abuse for some reason.

**Comment by XhmikosR** [comment]
@dschaper should we close this PR in favor of #237?

**Comment by dschaper** [comment]
Either one, as long as the other one gets the corrections that have been requested.

**Comment by XhmikosR** [comment]
Alright, closing this one in favor of #237

**Pull request closed without merging**
